select * from customer limit 10

--Business Problems

-- Q1) What is the total revenue generated by male vs female customers ?

	select 
	gender,
	sum(purchase_amount) as revenue
	from customer
	group by gender

--Q2) Which customers used a discount but still spent more the average purchase amount ?

	SELECT
    customer_id,
    purchase_amount
    FROM customer
    WHERE discount_applied = 'Yes'
    AND purchase_amount >= (
      SELECT AVG(purchase_amount) FROM customer
  );

--Q3) What are the top 5 products with the highest avg value rating ?

    SELECT
    item_purchased,
    ROUND(AVG(review_rating)::numeric, 2) AS avg_review_rating
	FROM customer
	GROUP BY item_purchased
	order by 2 desc
	limit 5
	
--Q4) Compare the avg Purchase amount between standard and express shipping.

	select 
	shipping_type,
	Round(avg(purchase_amount),2) AS avg_purchase_amt
	from customer
	where shipping_type in ('Standard' , 'Express')
	group by shipping_type

--Q5) DO Subscribed Customers spend more ? Compare avg spend and total revenue 
	--betweem subscribers and non-subscribers

	select
	subscription_status,
	count(customer_id) as total_customers,
	Round(avg(purchase_amount),2) as avg_spend,
	Round(sum(purchase_amount),2) as total_revenue 
	from customer
	group by subscription_status 
	order by total_revenue, avg_spend desc

--Q6) Which 5 products have the highest percentage of purchase with discounts applied ?

	
	SELECT 
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
	FROM customer
	GROUP BY item_purchased
	ORDER BY discount_rate DESC
	LIMIT 5;
